server:
  port: 8081
spring:
  datasource:
    username: postgres
    password: 2211
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    hiddenmethod:
      filter:
        enabled: true